// <auto-generated />
using System;
using CRM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRM.Migrations
{
    [DbContext(typeof(CRMContext))]
    [Migration("20200422134635_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("CRM.Models.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FullName");

                    b.Property<string>("Phone");

                    b.HasKey("ID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("CRM.Models.CustomerAccount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CustomerId");

                    b.Property<int>("FilialId");

                    b.HasKey("ID");

                    b.HasIndex("CustomerId");

                    b.HasIndex("FilialId");

                    b.ToTable("CustomerAccount");
                });

            modelBuilder.Entity("CRM.Models.CustomerAccountProduct", b =>
                {
                    b.Property<int>("CustomerAccoountId");

                    b.Property<int>("ProductId");

                    b.Property<int>("ID");

                    b.HasKey("CustomerAccoountId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("CustomerAccountProduct");
                });

            modelBuilder.Entity("CRM.Models.Filial", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Filial");
                });

            modelBuilder.Entity("CRM.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("CRM.Models.Role", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("CRM.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("FilialID");

                    b.Property<string>("Login");

                    b.Property<string>("Password");

                    b.HasKey("ID");

                    b.HasIndex("FilialID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("CRM.Models.UserRole", b =>
                {
                    b.Property<int>("RoleId");

                    b.Property<int>("UserId");

                    b.Property<int>("ID");

                    b.HasKey("RoleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("CRM.Models.CustomerAccount", b =>
                {
                    b.HasOne("CRM.Models.Customer", "Customer")
                        .WithMany("CustomerAccounts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CRM.Models.Filial", "Filial")
                        .WithMany()
                        .HasForeignKey("FilialId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CRM.Models.CustomerAccountProduct", b =>
                {
                    b.HasOne("CRM.Models.CustomerAccount", "CustomerAccount")
                        .WithMany("CustomerAccountProducts")
                        .HasForeignKey("CustomerAccoountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CRM.Models.Product", "Product")
                        .WithMany("CustomerAccountProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CRM.Models.User", b =>
                {
                    b.HasOne("CRM.Models.Filial")
                        .WithMany("Users")
                        .HasForeignKey("FilialID");
                });

            modelBuilder.Entity("CRM.Models.UserRole", b =>
                {
                    b.HasOne("CRM.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CRM.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
